version: '3.8'

volumes:
  freeport_bch_wallet_volume:
  freeport_bch_volume:
  db:
    driver: local

networks:
  freeport:
    external: true

  api:
    container_name: freeport-bch
    image: freeport/freeport-bch
    restart: on-failure
    build:
        context: ./
        dockerfile: Dockerfile
    volumes:
        - ./:/app
        - freeport_wallet_bch:/home/droid/freeport/data
    ports:
      - '6010:6010'
    networks:
      - freeport
