version: '3.8'


networks:
  freeport:
    external: true
services:
  bchwallet:
    container_name: freeport-bch
    image: freeport/freeport-bch
    restart: on-failure
    build:
        context: ./
        dockerfile: ./Dockerfile
    volumes:
        - ./:/app
        - freeport_wallet_bch:/home/droid/freeport/data
    ports:
      - '5085:5085'
    networks:
      - freeport
volumes:

  freeport_wallet_bch:
  db:
    driver: local
